import "./globals.css";
import { Roboto_Flex } from "next/font/google";
import { Navbar } from "@/components/navbar/page.js";
import Footer from "@/components/footer/page.js";
import BackToTop from "@/components/backToTop/page";

const roboto = Roboto_Flex({
	subsets: ["latin"],
});

export const metadata = {
	title: "The Pet Store",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={roboto.className}>
				<Navbar />
				{children}
				<Footer />
				<BackToTop/>
			</body>
		</html>
	);
}
